
import java.sql.ResultSet;
import java.util.List;
import java.util.ArrayList;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author vasilis
 */
public class FullWorkout extends javax.swing.JDialog {

    GymSupportUI mainFrame;
    private User currentUser;
    
    DefaultListModel dlf = new DefaultListModel();
    DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<String>();
    /**
     * Creates new form FullWorkout
     */
    public FullWorkout(GymSupportUI mainFrame, boolean modal) {
        super(mainFrame, modal);
        this.mainFrame = mainFrame;
        currentUser = mainFrame.getCurrentUser();
        initComponents();
        this.setLocationRelativeTo(mainFrame);
        
        expertiseList.setModel(dlf);
        expertiseList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        for (String expertise : Middleware.getInstance().getExpertise().keySet()) {
            dlf.addElement(expertise);
        }
        
        trainerCombo.setModel(comboModel);
    }
    
    private List<Trainer> getTrainersByExpertise(String expertise) {
        
        List<Trainer> trainers = new ArrayList<>();
        try {
            ResultSet rs = PGClass.getInstance().executeSelectQuery("select trainer_code from trainer_expertise where expertise_code = '" + expertise + "'");
            while (rs.next()) {
                trainers.add(Middleware.getInstance().getTrainers().get(rs.getString("trainer_code")));
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
            System.out.println("DB Failure!");
             return trainers;
        }
        
        return trainers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        expertiseList = new javax.swing.JList<>();
        trainerCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        trainerProfileArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Workout Type:");

        expertiseList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                expertiseListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(expertiseList);

        trainerCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainerComboActionPerformed(evt);
            }
        });

        trainerProfileArea.setColumns(20);
        trainerProfileArea.setLineWrap(true);
        trainerProfileArea.setRows(5);
        jScrollPane2.setViewportView(trainerProfileArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trainerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(trainerCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(225, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expertiseListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_expertiseListValueChanged
        // TODO add your handling code here:
        List<Trainer> trainers = getTrainersByExpertise(expertiseList.getSelectedValue());
        comboModel.removeAllElements();
        for (Trainer tr : trainers) {
            comboModel.addElement(tr.getCode());
        }
    }//GEN-LAST:event_expertiseListValueChanged

    private void trainerComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainerComboActionPerformed
        // TODO add your handling code here:
        Trainer tr = Middleware.getInstance().getTrainers().get(trainerCombo.getSelectedItem());
        if (tr == null) {
            return;
        }
        String s = "Hi " + mainFrame.getCurrentUser().getName() + ", I am " + tr.getName() + ",\n\n";
        s += tr.getProfile();
        trainerProfileArea.setText(s);
    }//GEN-LAST:event_trainerComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FullWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FullWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FullWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FullWorkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FullWorkout dialog = new FullWorkout((GymSupportUI) new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> expertiseList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> trainerCombo;
    private javax.swing.JTextArea trainerProfileArea;
    // End of variables declaration//GEN-END:variables
}
